export const ACCOUNT_ICONS = [
  'wallet-outline',
  'cash-outline',
  'card-outline',
  'business-outline',
  'home-outline',
  'shield-outline',
  'layers-outline',
  'scan-outline',
  'swap-horizontal-outline',
  'receipt-outline',
  'trending-up-outline',
  'trending-down-outline',
  'pie-chart-outline',
  'bar-chart-outline',
  'analytics-outline',
  'stats-chart-outline',
  'briefcase-outline',
  'storefront-outline',
  'pricetag-outline',
  'ellipsis-horizontal-outline',
] as const;
